server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
zuul: 
  prefix: /syh  #给所有的服务名设置统一的前缀
  ignored-services: "*" #表示匹配所有的服务
  routes: 
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/** #表示把microservicecloud-dept服务映射成mydept
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
 
info:
  app.name: syh-microcloud
  company.name: www.syh.com
  build.artifactId: microservicecloud-zuul-gateway
  build.version: 0.0.1-SNAPSHOT
 

